### ISSUE TITLE
Can't Configure Plugin

### ISSUE THREAD

**Issue by bennun** [joshsten/redmine_jchat#18]
Hi, very nice plugin! I was able to successfully install it on my Redmine server (1.1.2 stable, with Ubuntu 10.02, Mysql). I would put in your instructions to reboot after the rake. Anyway, the JChat plugin shows up, but I can't edit the last two: Recent Messages and polling frequency. Is this by design? The box for the entry is positioned to the left, over the beginning text. Very weird. Chat works though, so kudos!

**Comment by joshsten** [comment]
The options in the configure dialog are more stubs for future functionality. Some of them are internally implemented, but not "wired in". I put the subs in so that when other localize the plugin for other languages the localization encompasses some of the functionality I hope to add in the future. 

Thank you for your comments :)

Best Regards,
Josh
